### ISSUE TITLE
English language standard layout 

### ISSUE THREAD

**Issue by ithinkido** [SimonGolms/QLOCKGENERATOR#22]
When using the English standard layout, the words for 25 are written together. It would be better to have the "twenty" and "five" separated. 

https://github.com/SimonGolms/QLOCKGENERATOR/blob/a2488cf1db4a15b2751f0920db2dc24471626a86/src/app/configs/languages.ts#L61

from nTWENTYFIVEX
to nTWENTXYFIVE

**Comment by SimonGolms** [comment]
Hi @ithinkido, thanks for opening the issue. I know what you mean, but I used the front/text of the original manufacturer as comparison. As far as I know, the `EN` format is also configured in many firmwares of the DIY word clocks like this and also use the front/text of the original manufacturer as comparison. Therefore I want to be align with them.
However, the user can make further adjustments by its own.

**Comment by SimonGolms** [comment]
I just realized that it is even necessary to display e.g.: "IT IS TWENTYFIVE TO TWO".

**Comment by ithinkido** [comment]
> I just realized that it is even necessary to display e.g.: "IT IS TWENTYFIVE TO TWO".

Yes, it is needed for " IT IS TWENTY FIVE TO TWO" and "IT IS TWENTY FIVE PAST...." I can see your point about keeping with the original manufacturer layout. I only realised it after i had cut the face foil. I will cut a corrected version this week.
