### ISSUE TITLE
Use the Generator on Windows?

### ISSUE THREAD

**Issue by BjoeHrn** [SimonGolms/QLOCKGENERATOR#26]
Hi there,

is there a soulution to use the qlockgenerator on a windows mashine?
I have only a apache server with php and mysql with xampp and the main page is still white.

Thanks for helping.

**Comment by SimonGolms** [comment]
This is a NodeJS/Angular/NodeJS project and should run on all platforms. Just follow the [Getting Started](https://github.com/SimonGolms/QLOCKGENERATOR#getting-started) guide in the README to get a local development environment running. You can start a build process with the following command: `ionic build --prod --engine=browser`. See [Ionic Documentation](https://ionicframework.com/docs/cli/commands/build)

The content of the `www` can be copied to your Server. A database connection is not necessary.

_Hint_: If you are running the site under a subdomain, you have to change the base-href specification in the build process, e.g. `ionic build --prod --engine=browser -- --base-href /mySubDomain/`

**Comment by BjoeHrn** [comment]
I've installed a virtual maschine with a debain system - with your help, this way was very easy.
Thanks again :-)!
